import { HowToGuide } from './types';

export const SALAH_MAKRUH_GUIDE: HowToGuide = {
  id: 'salah-makruh',
  parentGroup: 'Salah',
  title: 'Makruh in Salah مكروهات الصلاة (Makruh)',
  subtitle: 'Salah Core · Hanafi (Nur al-Idah)',
  icon: 'report-problem',
  color: '#F9A825',
  intro: 'These 46 makruh acts in salah are from Hanafi fiqh study notes (Nur al-Idah based learning). They generally do not invalidate salah, but they reduce reward, adab, and focus.',
  sections: [
    {
      heading: '1) Leaving Required or Recommended Acts',
      steps: [
        { step: 1, title: 'Intentionally leaving out a wajib', detail: 'Deliberately abandoning a wajib act is makruh tahrimi and a serious deficiency.' },
        { step: 2, title: 'Intentionally leaving out a sunnah', detail: 'Deliberately abandoning an established sunnah of salah is makruh and blameworthy.' },
      ],
    },
    {
      heading: '2) Body Movements, Posture, and Dress (3-24)',
      steps: [
        { step: 3, title: 'Fidgeting with clothes or body', detail: 'Playing with clothing, beard, fingers, or body without need is makruh.' },
        { step: 4, title: 'Placing hands on the hips', detail: 'Standing in prayer with hands on hips is disliked.' },
        { step: 5, title: 'Letting cloth hang proudly or neglectfully', detail: 'Letting a cloth hang from shoulders in a prideful or careless manner is makruh.' },
        { step: 6, title: 'Plaiting or tying up the hair', detail: 'Tying or bunching hair for prayer in this manner is disliked.' },
        { step: 7, title: 'Allowing gaze to wander', detail: 'Looking around and not maintaining focused gaze harms khushu and is makruh.' },
        { step: 8, title: 'Sitting like a dog', detail: 'Adopting dog-like sitting posture in salah is makruh.' },
        { step: 9, title: 'Replying to salam by indication', detail: 'Responding to salam with gesture while praying is makruh.' },
        { step: 10, title: 'Sitting cross-legged without excuse', detail: 'Cross-legged sitting in salah without need is disliked.' },
        { step: 11, title: 'Doing minor unnecessary actions', detail: 'Small non-prayer actions are makruh when done without need.' },
        { step: 12, title: 'Anything that distracts the mind', detail: 'Actions that reduce concentration and khushu are makruh.' },
        { step: 13, title: 'Intertwining the fingers', detail: 'Interlocking fingers during salah is disliked.' },
        { step: 14, title: 'Resting forearms on the ground in sajdah', detail: 'Forearms should not be spread flat on the ground like this in sajdah.' },
        { step: 15, title: 'Turning fingers or toes away from qiblah', detail: 'Hands and feet should be oriented correctly toward qiblah as taught.' },
        { step: 16, title: 'Not placing hands on knees in ruku', detail: 'Hands should hold the knees in ruku according to proper method.' },
        { step: 17, title: 'Not placing right over left while standing', detail: 'Leaving the established hand placement in qiyam without excuse is makruh.' },
        { step: 18, title: 'Stretching arms unnecessarily', detail: 'Unneeded arm extension and motion is disliked in salah.' },
        { step: 19, title: 'Sajdah on fold of turban without need', detail: 'Making sajdah on folded turban cloth without necessity is makruh.' },
        { step: 20, title: 'Sajdah with forehead only, not nose, without excuse', detail: 'Without valid excuse, sajdah should include both forehead and nose.' },
        { step: 21, title: 'Leaving upper body uncovered despite ability', detail: 'Failing to cover properly while being able to cover is makruh.' },
        { step: 22, title: 'Head wrap leaving middle exposed', detail: 'Tying cloth around head while leaving middle exposed in this manner is disliked.' },
        { step: 23, title: 'Wrapping tightly so hands cannot move', detail: 'Wrapping clothing in a way that blocks proper hand movement is makruh.' },
        { step: 24, title: 'Leaving right shoulder uncovered', detail: 'Praying with right shoulder uncovered without valid reason is disliked.' },
      ],
    },
    {
      heading: '3) Recitation Order and Surah Choices (25-31)',
      steps: [
        { step: 25, title: 'Reciting Quran outside required standing posture', detail: 'In units where standing is required, recitation should be done in qiyam.' },
        { step: 26, title: 'Lengthening first rakah of nafl much more than second', detail: 'Excessive unequal length between first and second rakah in nafl is makruh.' },
        { step: 27, title: 'Lengthening second rakah more than first', detail: 'Making the second rakah longer than the first in any salah is disliked.' },
        { step: 28, title: 'Repeating same surah more than once in same rakah of fard', detail: 'Repeating a surah in the same fard rakah in this way is makruh.' },
        { step: 29, title: 'Reciting earlier surah in second rakah', detail: 'In second rakah, reciting a surah that comes before the first-rakah surah is disliked.' },
        { step: 30, title: 'Skipping short surah between recited surahs', detail: 'Reciting two surahs in two rakahs while skipping one short surah in between is makruh.' },
        { step: 31, title: 'Fixing only one surah always', detail: 'Always sticking to one surah and abandoning variety is disliked.' },
      ],
    },
    {
      heading: '4) Personal Conduct During Prayer (32-34)',
      steps: [
        { step: 32, title: 'Covering nose or mouth', detail: 'Covering the nose or mouth during salah without need is makruh.' },
        { step: 33, title: 'Yawning', detail: 'Yawning in salah is disliked; one should resist and suppress it as much as possible.' },
        { step: 34, title: 'Closing the eyes', detail: 'Closing eyes without need is makruh in normal circumstances.' },
      ],
    },
    {
      heading: '5) Place, Environment, and Imam Positioning (35-46)',
      steps: [
        { step: 35, title: 'Praying in a bathroom', detail: 'Performing salah in a bathroom is makruh.' },
        { step: 36, title: 'Praying in a graveyard', detail: 'Praying in graveyard areas is makruh except where juristic exceptions apply.' },
        { step: 37, title: 'Praying on property without permission', detail: 'Praying on another person\'s property without permission is disliked and sinful.' },
        { step: 38, title: 'Praying near impurity', detail: 'Performing salah near filth/impurity is makruh and harms prayer decorum.' },
        { step: 39, title: 'Praying with urge to relieve oneself', detail: 'Praying while needing urination or defecation is makruh due to poor concentration.' },
        { step: 40, title: 'Praying while hungry when desired food arrives', detail: 'If food is present and one is hungry and distracted, praying first is makruh.' },
        { step: 41, title: 'Praying in shabby clothing', detail: 'Wearing neglected, shabby clothes in prayer despite better options is disliked.' },
        { step: 42, title: 'Keeping head uncovered unnecessarily', detail: 'Leaving head uncovered without reason is considered makruh in this teaching context.' },
        { step: 43, title: 'Imam standing fully inside mihrab', detail: 'It is makruh for imam to stand fully inside the mihrab recess.' },
        { step: 44, title: 'Imam standing too high above followers', detail: 'Standing on a platform more than about one cubit above followers is disliked.' },
        { step: 45, title: 'Not placing sutrah where people may pass', detail: 'When people are likely to pass in front, leaving sutrah is makruh.' },
        { step: 46, title: 'Praying on common pathway', detail: 'Praying directly on a path commonly used by people is disliked.' },
      ],
    },
  ],
  notes: [
    'Primary reference: Nur al-Idah (Nur ul Idah), section on makruhat al-salah.',
    'Some items may be classified by scholars with differing levels of dislike (makruh tanzihi vs makruh tahrimi) depending on details.',
    'For fatwa-level decisions in your local context, consult a qualified Hanafi mufti or scholar.',
  ],
};
